---
title: "SCINET"
author: "Konrad Thorner"
date: "8/10/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
devtools::install_github("shmohammadi86/NetLibR")
devtools::install_github("shmohammadi86/ACTIONet", ref = "R-release")
BiocManager::install("batchelor")
devtools::install_github("immunogenomics/harmony")
install.packages("R.utils")
```

```{r}
library(ACTIONet)
library(SingleCellExperiment)
library(igraph)
```

```{r}
run.SCINET.clusters.konrad <- function(ace, specificity.slot.name, G = NULL, min.edge.weight = 2, spec.sample_no = 1000, thread_no = 8, compute.topo.specificity = T) {
  library(SCINET)
  
  print("Preprocessing the baseline interactome")
  if (is.null(G)) {
    if (!exists("PCNet")) {
      data("PCNet")
    }
    Adj = PCNet
  } else if (is.matrix(G) | is.sparseMatrix(G)) {
    Adj = as(G, "sparseMatrix")
    Adj@x = rep(1, length(Adj@x))
  } else if (is.igraph(G)) {
    Adj = as(get.adjacency(G), "sparseMatrix")
  }
  
  
  if (!(specificity.slot.name %in% names(rowMaps(ace)))) {
    message(sprintf("%s does not exist in rowMaps(ace)", specificity.slot.name))
  }
  
  gene.scores = as.matrix(log1p(rowMaps(ace)[[specificity.slot.name]]))
  
  
  common.genes = intersect(rownames(gene.scores), rownames(Adj))
  if (length(common.genes) == 0) {
    print("No common genes found. Check rownames (or vertex names) for the input graph")
    return(ace)
  }
  A = gene.scores[common.genes, ]
  G = Adj[common.genes, common.genes]
  
  
  print("Constructing networks")
  gene.activity.scores = SCINET::compute_gene_activities_full(A = A, thread_no = thread_no)
  cellstate.nets = SCINET::construct_cell_networks(net = G, gene_activities = gene.activity.scores,
                                                   thread_no = thread_no)
  cellstate.nets.list = as.list(cellstate.nets)
  
  print("Post-processing networks\n")
  cellstate.nets.list.igraph = lapply(cellstate.nets.list, function(G.Adj) {
    G.Adj@x[G.Adj@x < min.edge.weight] = 0
    filter.mask = Matrix::colSums(G.Adj) == 0
    G = igraph::graph_from_adjacency_matrix(G.Adj[!filter.mask, !filter.mask],
                                            mode = "undirected", weighted = T)
    V(G)$name = common.genes[!filter.mask]
    if (compute.topo.specificity == TRUE) {
      z.scores = topo.spec(G, spec.sample_no)
      V(G)$specificity = 1/(1 + exp(-z.scores))
    }
    
    return(G)
  })
  
  if (is.null(colnames(gene.scores))) {
    names(cellstate.nets.list.igraph) = 1:ncol(gene.scores)
  } else {
    names(cellstate.nets.list.igraph) = colnames(gene.scores)
  }
  return(cellstate.nets.list.igraph)
}

main_loop <- function(ace_obj) {
  print(ace_obj)
  ace <- reduce.ace(ace_obj)
  ace <- run.ACTIONet(ace)
  celltypes <- levels(ace$CellType)
  ace <- compute.cluster.feature.specificity(ace, celltypes, "celltype_specificity_scores")
  Celltype.specific.networks <- run.SCINET.clusters.konrad(ace, specificity.slot.name = "celltype_specificity_scores_feature_specificity", G=bioplex_graph)
  return(Celltype.specific.networks)
}

#If beginning with Seurat objects, use ACTIONet::import.ace.from.Seurat(seurat_obj)
ace_list <- readRDS("/home/konrad/Downloads/Summer/Data/sc_compendium_ace.rds")
bioplex_graph <- graph_from_data_frame(as.matrix(read.delim("/home/konrad/Downloads/Summer/Data/bioplex_ref.tsv", stringsAsFactors = FALSE)[,5:6]), directed = FALSE)
#Returns a list, each element corresponding to a dataset, of lists, each element corresponding to a cell type.
csn_list <- lapply(ace_list, function(x) main_loop(x))
saveRDS(csn_list,"/home/konrad/Downloads/Summer/Data/csn.rds")
```

